import "@styles/global.css"

export const metadata = {
  description: "Generated by create next app",
  title: "Next13 TypeScript Template",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
